
DELIMITER //
CREATE FUNCTION TRAERPLANTEL($IDPLANTEL INT) RETURNS INT 
BEGIN
	IF(SELECT idplantel FROM PLANTEL WHERE idplantel = $IDPLANTEL) THEN
		RETURN 1;
	END IF;
    RETURN 0;
END//;
DELIMITER ;

DELIMITER //
CREATE PROCEDURE ALTAPLANTEL( $IDPLANTEL INT,$EDAD INT, $GENETICA_GALLINA INT, $FECHA_ENTRADA DATE, $PRECIOcOMPRA FLOAT, $GALPON_IDGALPON INT)
BEGIN
	IF(TRAERGENETICA($GENETICA_GALLINA) = 0 AND TRAERGALPON($GALPON_IDGALPON) = 0 ) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE LA GENETICA NI EL GALPON';
	ELSE IF (TRAERGENETICA($GENETICA_GALLINA) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE LA GENETICA ';
	ELSE IF (TRAERGALPON($GALPON_IDGALPON) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE EL GALPON';
	ELSE IF(TRAERPLANTEL($IDPLANTEL) = 1) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'YA EXISTE EL PLANTEL';
	ELSE
    
	INSERT INTO plantel (idplantel,edad,genetica_gallina,fecha_Entrada,precioCompra,galpon_idgalpon) VALUES
    ( $IDPLANTEL, $EDAD , $GENETICA_GALLINA, $FECHA_ENTRADA, $PRECIOcOMPRA , $GALPON_IDGALPON);
    
	END IF;
    END IF;
    END IF;
    END IF;
    
   END//;
   DELIMITER ;

DROP PROCEDURE ALTAPLANTEL;

CALL ALTAPLANTEL(1,12,1,'1992-05-02',32,1);

DELIMITER //
CREATE PROCEDURE MODIFICACIONPLANTEL( $IDPLANTEL INT,$EDAD INT, $GENETICA_GALLINA INT, $FECHA_ENTRADA DATE, $PRECIOcOMPRA FLOAT, $GALPON_IDGALPON INT)
BEGIN
	IF(TRAERGENETICA($GENETICA_GALLINA) = 0 AND TRAERGALPON($GALPON_IDGALPON) = 0 ) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE LA GENETICA NI EL GALPON';
	ELSE IF (TRAERGENETICA($GENETICA_GALLINA) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE LA GENETICA ';
	ELSE IF (TRAERGALPON($GALPON_IDGALPON) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE EL GALPON';
	ELSE IF(TRAERPLANTEL($IDPLANTEL) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE EL PLANTEL';
	ELSE
	UPDATE plantel SET
    edad = $EDAD,
    genetica_gallina = $GENETICA_GALLINA,
    fecha_Entrada = $FECHA_ENTRADA,
    precioCompra = $PRECIOcOMPRA ,
    galpon_idgalpon = $GALPON_IDGALPON
    where idplantel = $IDPLANTEL;
    
	END IF;
    END IF;
    END IF;
    END IF;
    
   END//;
   DELIMITER ;
DROP PROCEDURE MODIFICACIONPLANTEL;
CALL MODIFICACIONPLANTEL(1,20,1,'1998-11-30',09,1);
   
DELIMITER //
CREATE PROCEDURE BAJAPLANTEL($IDPLANTEL INT)
BEGIN
   IF(TRAERPLANTEL($IDPLANTEL) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE EL PLANTEL';
	END IF;
    DELETE FROM plantel WHERE idplantel = $IDPLANTEL;
END//;
DELIMITER ;
DROP PROCEDURE BAJAPLANTEL;
CALL BAJAPLANTEL(1);
    
create index algo on plantel(edad,fecha_Entrada);

