DELIMITER //
CREATE FUNCTION TRAERCLIENTE($CUIT VARCHAR(11)) RETURNS INT
BEGIN
	IF ( SELECT cuit from cliente where cuit = $CUIT ) THEN
		RETURN 1;
	END IF;
    RETURN 0 ;
END//;
DELIMITER ;
    
DELIMITER //    
CREATE PROCEDURE ALTACLIENTE($NOMBRE VARCHAR(45), $DIRECCION VARCHAR(45), $NUMERO VARCHAR(45), $LOCALIDAD VARCHAR(45), $CUIT VARCHAR(11))
BEGIN
	IF(TRAERCLIENTE($CUIT) = 1) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'YA EXISTE EL CLIENTE';
	END IF;
	INSERT INTO cliente(nombre,direccion,numero,localidad,cliente.cuit) VALUES ($NOMBRE, $DIRECCION, $NUMERO, $LOCALIDAD, $CUIT);

END //;
DELIMITER ;

SELECT * FROM CLIENTE;
DROP PROCEDURE ALTACLIENTE;
drop function TRAERCLIENTE;
CALL ALTACLIENTE('ALAN','CORDOBA','2345','MOSSERRANT','12312312344');


DELIMITER //
CREATE PROCEDURE BAJACLIENTE($CUIT VARCHAR(11))
BEGIN
	IF(TRAERCLIENTE($CUIT) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = ' NO EXISTE EL CLIENTE A DAR DE BAJA';
	END IF;
    DELETE FROM cliente WHERE cuit = $CUIT;
END//;
DELIMITER ;

CALL BAJACLIENTE('12312312344');

DELIMITER //    
CREATE PROCEDURE MODIFICARCLIENTE($NOMBRE VARCHAR(45), $DIRECCION VARCHAR(45), $NUMERO VARCHAR(45), $LOCALIDAD VARCHAR(45), $CUIT VARCHAR(11))
BEGIN
	IF(TRAERCLIENTE($CUIT) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE EL CLIENTE A MODIFICAR';
	END IF;
	UPDATE cliente SET
    nombre = $NOMBRE ,
    direccion = $DIRECCION ,
    numero  = $NUMERO,
    localidad  = $LOCALIDAD 
    WHERE cuit = $CUIT;
END //;
DELIMITER ;

CALL MODIFICARCLIENTE('OSCAR','PEGUAJO','1234', 'NOSESABE','12312312344');

