
DELIMITER //
CREATE FUNCTION TRAERGRANJA($IDGRANJA INT) RETURNS INT
BEGIN
	IF(SELECT idGranja FROM granja where idGranja = $IDGRANJA) THEN
		RETURN 1;
	END IF;
    RETURN 0;
END//;
DELIMITER ;



DELIMITER //
CREATE PROCEDURE ALTAGRANJA($NOMBRE VARCHAR(45), $IDGRANJA INT, $CABAÑA_CUIT VARCHAR(11) )
BEGIN
	IF(TRAERGRANJA($IDGRANJA) = 1) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'YA EXISTE LA GRANJA';
	ELSE IF(TRAERCABAÑA($CABAÑA_CUIT) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE LA CABAÑA';
	ELSE 
		INSERT INTO granja(nombre,idGranja,cabaña_cuit) VALUES ($NOMBRE,$IDGRANJA,$CABAÑA_CUIT);
	END IF;
    END IF;
END//;
DELIMITER ;

SELECT * FROM granja;
CALL ALTAGRANJA('LA GRANJERA',1,'12312312311');

DELIMITER //
CREATE PROCEDURE MODIFICARGRANJA($NOMBRE VARCHAR(45), $IDGRANJA INT, $CABAÑA_CUIT VARCHAR(11) )
BEGIN
	IF(TRAERGRANJA($IDGRANJA) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE LA GRANJA A MODIFICAR';
	ELSE IF(TRAERCABAÑA($CABAÑA_CUIT) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE LA CABAÑA';
	ELSE 
		UPDATE granja SET 
        nombre = $NOMBRE,
        cabaña_cuit = $CABAÑA_CUIT
        WHERE  idGranja = $IDGRANJA;
	END IF;
    END IF;
END//;
DELIMITER ;

CALL MODIFICARGRANJA('GRANJA',1,'12312312311')


DELIMITER //
CREATE PROCEDURE BAJAGRANJA($IDGRANJA INT)
BEGIN
	IF(TRAERGRANJA($IDGRANJA) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE LA GRANJA A ELIMINAR';
	END IF;
    DELETE FROM granja WHERE idGranja = $IDGRANJA;
END//;
DELIMITER ;
DROP PROCEDURE BAJAGRAN;
CALL BAJAGRANJA(2);
