DELIMITER //
CREATE FUNCTION TRAERGALPON($ID_GALPON INT) RETURNS INT 
BEGIN
	IF(SELECT idgalpon FROM galpon WHERE idgalpon = $ID_GALPON) THEN
		RETURN 1;
    END IF;
    RETURN 0;
END//;
DELIMITER ;
DELIMITER //
CREATE PROCEDURE ALTAGALPON($IDGALPON INT,$CANTIDAD_GALLINAS INT, $CABAÑA_CUIT VARCHAR(11), $GALPONERO_CUIL VARCHAR(11))
BEGIN
	IF(TRAERGALPONERO($GALPONERO_CUIL) = 0 AND TRAERCABAÑA($CABAÑA_CUIT) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = ' NO EIXSTE EL GALPONERO NI LA CABAÑÑA';
	ELSE IF(TRAERGALPONERO($GALPONERO_CUIL) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = ' NO EIXSTE EL GALPONERO';
	ELSE IF (TRAERCABAÑA($CABAÑA_CUIT) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = ' NO EIXSTE LA CABAÑÑA';
	ELSE IF (TRAERGALPON($IDGALPON) = 1) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = ' YA EXISTE EL GALPON ';
	ELSE
    INSERT INTO galpon(idgalpon,cantidad_gallinas,cabaña_cuit,galponero_cuil) VALUES ($IDGALPON,$CANTIDAD_GALLINAS, $CABAÑA_CUIT, $GALPONERO_CUIL);
	END IF;
    END IF;
    END IF;
    END IF;
   
END//;
DELIMITER ;
SELECT* FROM CABAÑA;
SELECT * FROM GALPONERO;
SELECT * FROM GALPON;
CALL ALTAGALPON(1,200,'12312312311','11111111111');

DELIMITER //
CREATE PROCEDURE MODIFICARGALPON($IDGALPON INT,$CANTIDAD_GALLINAS INT, $CABAÑA_CUIT VARCHAR(11), $GALPONERO_CUIL VARCHAR(11))
BEGIN
	IF(TRAERGALPONERO($GALPONERO_CUIL) = 0 AND TRAERCABAÑA($CABAÑA_CUIT) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = ' NO EIXSTE EL GALPONERO NI LA CABAÑÑA';
	ELSE IF(TRAERGALPONERO($GALPONERO_CUIL) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = ' NO EIXSTE EL GALPONERO';
	ELSE IF (TRAERCABAÑA($CABAÑA_CUIT) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = ' NO EIXSTE LA CABAÑÑA';
	ELSE IF (TRAERGALPON($IDGALPON) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = ' NO EXISTE EL GALPON ';
	ELSE
    UPDATE galpon SET
    cantidad_gallinas= $CANTIDAD_GALLINAS,
    cabaña_cuit = $CABAÑA_CUIT, 
    galponero_cuil =$GALPONERO_CUIL
    WHERE idgalpon = $IDGALPON;
	END IF;
    END IF;
    END IF;
    END IF;
   
END//;
CALL MODIFICARGALPON(1,-1,'12312312311','11111111111');

DELIMITER //
CREATE PROCEDURE BAJAGALPON($IDGALPON INT)
BEGIN
	IF (TRAERGALPON($IDGALPON) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = ' NO EXISTE EL GALPON ';
	ELSE
    DELETE FROM galpon WHERE idgalpon = $IDGALPON;
	END IF;
END//;
DELIMITER ;
DROP PROCEDURE BAJAGALPON;
CALL BAJAGALPON(1);


 delimiter //
CREATE TRIGGER upd_check BEFORE UPDATE ON galpon
       FOR EACH ROW
       BEGIN
           IF NEW.cantidad_gallinas < 0 THEN
               SET NEW.cantidad_gallinas = 0;

           END IF;
       END;//
 delimiter ;
 
 
    
    