
DELIMITER //
CREATE FUNCTION TRAERGALPONERO($CUIL VARCHAR(11)) RETURNS INT
BEGIN
	IF(SELECT cuil 	FROM GALPONERO WHERE cuil = $CUIL) THEN
		RETURN 1;
	END IF;
    RETURN 0;
END//;
DELIMITER ;

DELIMITER //
CREATE PROCEDURE ALTAGALPONERO($CANTIDADHUEVOOBTENIDO INT, $CANTIDADGAMUERTA INT, $CANTIDAD FLOAT, $TIPO_ALIMENTO VARCHAR(45), $CUIL VARCHAR(11))
BEGIN
	IF(TRAERGALPONERO($CUIL) = 1) THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'YA EXISTE EL GALPONERO';
    END IF;
    INSERT INTO galponero(cantidadhuevosObtenidos,cantidadGaMuerta,cantidad,tipo_alimento,cuil) values ($CANTIDADHUEVOOBTENIDO, $CANTIDADGAMUERTA, $CANTIDAD , $TIPO_ALIMENTO , $CUIL);
END//;
DELIMITER ;

SELECT * FROM GALPONERO;
CALL ALTAGALPONERO(12,43,1000,'MEZCLA GALLINA','11111111111');

DELIMITER //
CREATE PROCEDURE MODIFICARGALPONERO($CANTIDADHUEVOOBTENIDO INT, $CANTIDADGAMUERTA INT, $CANTIDAD FLOAT, $TIPO_ALIMENTO VARCHAR(45), $CUIL VARCHAR(11))
BEGIN
	IF(TRAERGALPONERO($CUIL) = 0) THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'NO EXISTE EL GALPONERO A MODIFICAR';
    ELSE  
		UPDATE galponero SET
        cantidadhuevosObtenidos = $CANTIDADHUEVOOBTENIDO,
        cantidadGaMuerta = $CANTIDADGAMUERTA,
        cantidad = $CANTIDAD,
        tipo_alimento = $TIPO_ALIMENTO
        WHERE cuil = $CUIL;
	END IF;
        
        
END//;
DELIMITER ;

CALL MODIFICARGALPONERO(30,30,2000,'MEZCLA','11111111111');


DELIMITER //
CREATE PROCEDURE BAJAGALPONERO($CUIL VARCHAR(11))
BEGIN
	IF(TRAERGALPONERO($CUIL) = 0) THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'NO EXISTE EL GALPONERO A ELIMINAR';
	END IF;
    DELETE FROM galponero where cuil = $CUIL;
END//;
DELIMITER ;

CALL BAJAGALPONERO('11111111111');
    