SELECT * FROM genetica;
DELIMITER //
CREATE FUNCTION TRAERGENETICA($IDGENETICA INT) RETURNS INT 
BEGIN
	if(SELECT idgenetica FROM genetica where idgenetica = $IDGENETICA) THEN
		RETURN 1;
	END IF;
		RETURN 0;
END//;
DELIMITER ;

DELIMITER //
CREATE PROCEDURE ALTAGENETICA( $IDGENETICA INT, $NOMBRE VARCHAR(45), $CABAÑA_CUIT VARCHAR(11))
BEGIN
	IF(TRAERGENETICA($IDGENETICA) = 1) THEN
		SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'YA EXISTE EL CLIENTE';
	END IF;
    IF(TRAERCABAÑA($CABAÑA_CUIT) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE LA CABAÑA';
    END IF;
    INSERT INTO genetica(idgenetica,nombre,cabaña_cuit) VALUES ($IDGENETICA,$NOMBRE,$CABAÑA_CUIT);
END//;
DELIMITER ;

CALL ALTAGENETICA(1,'YOQUESE','12312312311');
DROP PROCEDURE ALTAGENETICA;

DELIMITER //
CREATE PROCEDURE MODIFICARGENETICA($IDGENETICA INT,$NOMBRE VARCHAR(45),$CABAÑA_CUIT VARCHAR(11))
BEGIN
	
    IF(TRAERGENETICA($IDGENETICA) = 0 AND TRAERCABAÑA($CABAÑA_CUIT) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT ='NO EXISTE LA GENETICA NI LA CABAÑA';
	ELSE 
    IF(TRAERGENETICA($IDGENETICA) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE LA GENETICA A MODIFICAR';
	ELSE IF (TRAERCABAÑA($CABAÑA_CUIT) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE LA CABAÑA';
	ELSE
    UPDATE genetica SET
    idgenetica = $IDGENETICA,
    nombre = $NOMBRE,
	cabaña_cuit = $CABAÑA_CUIT
    WHERE idgenetica = $IDGENETICA;
	END IF;
    END IF;
    END IF;
END//;
DELIMITER ;

DROP PROCEDURE MODIFICARGENETICA;
CALL MODIFICARGENETICA(1,'PORAY','12312312311');
DELIMITER //
CREATE PROCEDURE BAJAGENETICA($IDGENETICA INT)
BEGIN
	if(TRAERGENETICA($IDGENETICA) = 0) THEN
		SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'NO EXISTE LA GENETICA A ELIMINAR';
	END IF;
	DELETE FROM genetica where idgenetica = $IDGENETICA ;
END //;
DELIMITER ;

DROP PROCEDURE BAJAGENETICA;

CALL BAJAGENETICA(1);


