
SELECT * FROM VENTA;


DELIMITER //
CREATE PROCEDURE REALIZARVENTA($IDGRANJA INT , $FECHA DATETIME, $CLIENTE_CUIT VARCHAR(11), $IDPRODUCTO INT)
BEGIN
	IF( TRAERGRANJA($IDGRANJA) = 0 ) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE LA GRANJA';
	ELSE IF(TRAERCLIENTE($CLIENTE_CUIT) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE EL CLIENTE';
	ELSE IF (TRAERPRODUCTO($IDPRODUCTO) = 0) THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'NO EXISTE EL PRODUCTO';
	ELSE
		INSERT INTO venta (granja_idGranja,fecha,cliente_cuit,idproducto) VALUES($IDGRANJA, $FECHA, $CLIENTE_CUIT, $IDPRODUCTO);
	END IF;
    END IF;
    END IF;
END//;
DELIMITER ;

SELECT * FROM CLIENTE;
SELECT * FROM VENTA;
CALL REALIZARVENTA(1,'2000-05-06',12312312344,1);